from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('index/', views.index, name='index'),
    path('viewmore/', views.viewmore,name='viewmore'),
    path('event1/', views.event1, name='event1'),
    path('event2/', views.event2, name='event2'),
    path('event3/', views.event3, name='event3'),
    path('event4/', views.event4, name='event4'),
    path('signup/', views.user_signup, name='signup'),
    path('login/', views.login_page, name='login'),
    path('forgot/',views.forgot, name='forgot'),
    path('pwdset', views.pwdset, name='pwdset'),
    path('padmin/', views.padmin, name='padmin'),
    path('accept/<str:pk>/', views.accept, name='accept'),
    path('reject/<str:pk>/', views.reject, name='reject'),
    path('agent_signup/', views.agent_signup, name='agent_signup'),
    path('photographer_signup/', views.photographer_signup, name='photographer_signup'),
    path('profileview',views.profileview, name='profileview'),
    path('profile-edit/<str:pk>/', views.profile_edit, name='profile-edit'),
    path('logout/', views.logoutUser, name='logout'),
    path('package/', views.package, name='package'),
    path('replyview/<str:nm>/',views.replyview, name='replyview'),
    path('agent_packages', views.agent_packages, name='agent_packages'),
    path('create/', views.create_package, name='create'),
    path('chatview/<str:nm>/',views.chatview, name='chatview'),
    path('reply/<str:nm>/',views.reply, name='reply'),
    path('areply/<str:nm>/',views.areply, name='areply'),
    path('viewphoto', views.viewphoto, name="viewphoto"),
    path('viewagent/', views.viewagent, name='viewagent'),
    path('package-det/<str:pk>/', views.package_details, name='package-det'),
    path('booking_success/', views.booking_success, name='booking_success'),
    path('bookinglist/', views.bookinglist, name='bookinglist'),
    path('agencies/', views.agencies, name='agencies'),
    path('agentlink/<str:nm>', views.agentlink, name='agentlink'),
    path('chat',views.chat, name='chat'),
    path('package-edit/<str:pk>/', views.package_edit, name='package-edit'),
    path('payment', views.payment, name='payment'),
    path('pay', views.pay, name='pay'),
    path('bookind-del/<str:pk>/', views.cancel_booking, name='booking-del'),
    path('package-status/<str:pk>/', views.package_status, name='package-status'),
    path('package-detail/<str:pk>/', views.user_detail, name='user-detail'),


]